<div class="footer">Generated by ModelMate &nbsp;·&nbsp; {now}</div>
{autoprint_script}
</body></html>"""

# ── 피처 정보 (예측 폼 생성용) ───────────────────────────
@app.get("/api/feature-info")
async def feature_info():
    X = STATE.get("X")
    if X is None: raise HTTPException(400, "모델 없음")
    encoders  = STATE.get("encoders", {})
    cat_cols  = STATE.get("cat_cols", [])
    col_labels = STATE.get("col_labels", {})
    features = []
    for col in X.columns:
        if col in cat_cols and col in encoders:
            features.append({
                "name": col,
                "label": col_labels.get(col, col),
                "type": "categorical",
                "options": encoders[col].classes_.tolist(),
            })
        else:
            features.append({
                "name": col,
                "label": col_labels.get(col, col),
                "type": "numeric",
                "min":  round(float(X[col].min()), 4),
                "max":  round(float(X[col].max()), 4),
                "mean": round(float(X[col].mean()), 4),
            })
    target_enc = STATE.get("target_encoder")
    return {
        "features": features,
        "target_col": STATE.get("target_col"),
        "task_type": STATE.get("task_type", "classification"),
        "target_classes": target_enc.classes_.tolist() if target_enc else None,
    }

# ── 단일 행 예측 ───────────────────────────────────────────
@app.post("/api/predict")
async def predict_single(body: dict):
    model = STATE.get("best_model"); X_train = STATE.get("X")
    if model is None: raise HTTPException(400, "모델 없음")
    encoders  = STATE.get("encoders", {})
    cat_cols  = STATE.get("cat_cols", [])
    features  = body.get("features", {})
    row = {}
    for col in X_train.columns:
        val = features.get(col)
        if val is None:
            row[col] = 0 if col in cat_cols else float(X_train[col].mean())
        elif col in cat_cols and col in encoders:
            try:   row[col] = int(encoders[col].transform([str(val)])[0])
            except: row[col] = 0
        else:
            try:   row[col] = float(val)
            except: row[col] = float(X_train[col].mean())
    X_input = pd.DataFrame([row], columns=X_train.columns)
    pred = model.predict(X_input)[0]
    task_type = STATE.get("task_type", "classification")
    result = {"task_type": task_type}
    if task_type == "regression":
        result["prediction"] = round(float(pred), 4)
    else:
        result["prediction"] = int(pred)
        target_enc = STATE.get("target_encoder")
        if target_enc is not None:
            result["prediction_label"] = str(target_enc.inverse_transform([int(pred)])[0])
            result["class_labels"] = target_enc.classes_.tolist()
        else:
            result["prediction_label"] = str(int(pred))
        if hasattr(model, "predict_proba"):
            proba = model.predict_proba(X_input)[0].tolist()
            result["probabilities"] = [round(p, 4) for p in proba]
            result["confidence"] = round(max(proba), 4)
